### ISSUE TITLE
Get current time

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#18]
We need to figure a good way to get the `current_time` for using them in the models ([e.g.](https://github.com/Waifod/quant_finance_models/blob/main/src/pricing/model/black_scholes.cpp#L30C11-L30C23)).

**Comment by waifod** [comment]
PR dealing with the issue https://github.com/Waifod/quant_finance_models/pull/60.

**Comment by david-alvarez-rosa** [comment]
Closing as completed. Thanks!
