### ISSUE TITLE
Pass correct asset to `GetAssetSpotPrice`, i.e. underlying instead of option

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#19]
We the correct asset to `GetAssetSpotPrice` ([code ref](https://github.com/Waifod/quant_finance_models/blob/main/src/pricing/model/black_scholes.cpp#L25)). Right now we are passing the action itself, instead of passing the underlying.

**Comment by waifod** [comment]
Addressed by PR https://github.com/Waifod/quant_finance_models/pull/46.

**Comment by david-alvarez-rosa** [comment]
Closing per above comment.

CC: @Waifod
