### ISSUE TITLE
Rely on specific class `AssetTicker` for asset ticker instead of using `std::string`

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#22]
We'd like to have the ticker abstracted in a way that we are not just using `std::string`, but its own class `AssetTicker`.

**Comment by waifod** [comment]
Tackled via PR https://github.com/Waifod/quant_finance_models/pull/65.

**Comment by waifod** [comment]
PR https://github.com/Waifod/quant_finance_models/pull/65 merged. Closing issue.
