### ISSUE TITLE
Decide on copyright notice and make it consistent across files

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#29]
Decide on copyright notice and make it consistent across files.

**Comment by waifod** [comment]
I propose the following very minimal copyright notice.

```
/* 
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2023 David Alvarez Rosa, Matteo Durante
 */
```
The SPDX-License-Identifier refers to [this list](https://spdx.org/licenses/), which provides links to the actual licenses. Our names are ordered alphabetically.

**Comment by david-alvarez-rosa** [comment]
Oh nice, looks good!

TIL about SPDX.

**Comment by waifod** [comment]
PR https://github.com/Waifod/quant_finance_models/pull/67 merged. Closing issue.
