### ISSUE TITLE
Investigate about CI / CD with GitHub actions

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#34]
At minimal, we need to be able to setup an automated build at PR stage.

**Comment by david-alvarez-rosa** [comment]
Should be solved by #43.

**Comment by waifod** [comment]
Thanks! PR approved and merged. Keeping the issue open while we confirm that it's solved.

**Comment by waifod** [comment]
Things are working as expected. Closing the issue.
