### ISSUE TITLE
Think about adding Unit Testing to the project

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Waifod/quant_finance_models#35]
We need to align first on UT framework — probably Google's ones (`gmock` and `gtest`). TBD.

**Comment by waifod** [comment]
I would argue in favour of `GMock+GTest` since they will be maintained for a long time. An alternative would be `Turte+BoostTest`, but `Turtle` is maintained by just one guy.

**Comment by david-alvarez-rosa** [comment]
Yeah, sounds good to me!

**Comment by waifod** [comment]
Tackled via PR https://github.com/Waifod/quant_finance_models/pull/71. Closing.
